### ISSUE TITLE
Doesn't pull all entities for specific site

### ISSUE THREAD

**Issue by moderndeveloperllc** [openlink/structured-data-sniffer#1]
Not sure if this is an issue with the structure of this specific site's code, or the plugin.
```
https://www.allcarepharmacy.com/
```
The plugin only pulls three entities. You can see on the [Structured Data Linter results](http://linter.structured-data.org/?url=https:%2F%2Fwww.allcarepharmacy.com) for the page, there are many more it should be picking up.

**Comment by openlink** [comment]
I will contact development to have a look at it.

**Comment by smalinin** [comment]
The ```https://www.allcarepharmacy.com/``` is contained an unnamed subItems.
For example:

**Comment by smalinin** [comment]
Will be fixed in ver:2.3.0
