### ISSUE TITLE
Unable to view XML in Firefox

### ISSUE THREAD

**Issue by espen** [openlink/structured-data-sniffer#12]
When I have this add-on enabled I am unable to view XML pages in Firefox. The console shows:

```
XML Parsing Error: not well-formed Location: Line Number 1, Column 22:
```

If I disable the OpenLink Structured Date Sniffer add-on then the XML page displays correctly.

**Comment by smalinin** [comment]
Could you give an example of XML file with proble ?

**Comment by espen** [comment]
This might be related to something else. So it works for all XML-pages except for locally served ones (using .test TLD). Perhaps there are some security permissions either in Firefox or with this add-on that causes different behaviour for .test TLD?

**Comment by TallTed** [comment]
@espen - Have you tested the same XML file when served from both `.test` and some other TLD, so we can be sure the `.test` TLD should be our area of focus?

**Comment by smalinin** [comment]
@espen  Update Firefox OSDS  to latest version 2.16.19 from Firefox Addons store, it must resolve your problem.
Also this version has new settings option `[x] Try to handle XML files as RDF`, you could uncheck it for disable handle of XML data.
