### ISSUE TITLE
Signed Firefox Plugin

### ISSUE THREAD

**Issue by zicklag** [openlink/structured-data-sniffer#15]
This is a great plugin! It was *extremely* useful for helping me debug as I add microdata to my website.

It would be appreciated if there was a signed Firefox plugin, though, so that I can install the plugin permanently.

**Comment by smalinin** [comment]
The signed version could be installed from Mozilla Add-ons catalog [OpenLink Structured Data Sniffer](https://addons.mozilla.org/en-US/firefox/addon/openlink-structured-data-sniff/)

**Comment by zicklag** [comment]
Oh, thank you. I didn't see a link to the Mozilla catalog, so I didn't think to look.
