### ISSUE TITLE
Europeana set a new version in production

### ISSUE THREAD

**Issue by salgo60** [openlink/structured-data-sniffer#17]
**Newbie question:** I now get an error at Europeana after a new release in Europeana

_JSON-LD discovered, but fails syntax checking by parser:
--
jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context._

**on page** [people/24551-rosa-mullodzhanova.html](https://www.europeana.eu/portal/en/explore/people/24551-rosa-mullodzhanova.html)

![image](https://user-images.githubusercontent.com/14206509/77131851-88eda580-6a5d-11ea-8556-c06ad10f27b5.png)

**Question**: Is this a problem in the sniffer or should Europeana change something

**Comment by smalinin** [comment]
Now it works properly, may be something was updated on your site already.
![err_github_17](https://user-images.githubusercontent.com/765462/77192332-1dbcd580-6b28-11ea-9309-96aa757692da.png)
Anyway you could click on `View or Download ...` button for recheck JSON-LD data on your page,
so we will be able to look on the problem JSON-LD source code.
