### ISSUE TITLE
Sanitation check for HTML content not strict enough

### ISSUE THREAD

**Issue by deiu** [openlink/structured-data-sniffer#2]
There's some missing sanitation/escaping of HTML in certain case, such as for `schema:mainContentOfPage` objects.

For example, using the plugin on the page at https://github.com/deiu/html-sanitation/blob/master/README.md displays the select element generated by the keygen element.

**Comment by openlink** [comment]
Development is looking into this issue now.

**Comment by smalinin** [comment]
Will be fixed in ver:2.3.0
