### ISSUE TITLE
Firefox asking for new permission "Block content on any page"

### ISSUE THREAD

**Issue by ernstki** [openlink/structured-data-sniffer#26]
Hi all, this is not a bug report, but really a question about why this extension [requests the `webRequestBlocking` permission](https://github.com/openlink/structured-data-sniffer/commit/44827ba50ebcb71ccc1cd4f489e3b797facddaa5#r149086727)?

If Firefox is asking _just_ now, that could be just a weird Firefox thing; a bug, or just some corner case . I looks like I have 3.3.10 installed, from June 2024, but I usually keep it disabled in Firefox's settings unless I need it. Let's not get fixated on the Firefox thing, though.

The commit that changed that was 44827ba50ebcb71ccc1cd4f489e3b797facddaa5, in 2016. Does anyone remember anymore why that permission was requested? I guess it's fine, since most extensions don't even bother and ask for "all data on all websites" permission, but it got me curious is all.

**Comment by ernstki** [comment]
By the way, how is https://github.com/openlink different from https://github.com/OpenLinkSoftware? I'm not sure which to use, but this GitHub repository is the one pointed to by the a.m.o extension page.

If they're both legitimately under control of [OpenLink Software](https://www.openlinksw.com/company/) and the original authors of this extension, then I guess it's fine, but if the company disappeared and the web site is just being kept up by scammers, crypto/AI bros, or someone trying to ship malware as a part of a trusted browser extension, I'd like to know so I can move on.

**Comment by smalinin** [comment]
It is required for code in background.js , for handle data loading based on Content-Type in HTTP header for turtle, json-ld and etc. NOTE also, this is outdated repo, the actual repo => https://github.com/OpenLinkSoftware/OSDS_extension

**Comment by smalinin** [comment]
>  By the way, how is https://github.com/openlink different from https://github.com/OpenLinkSoftware? I'm not sure which to use, but this GitHub repository is the one pointed to by the a.m.o extension page.

Both places are belong to OpenLink Software , we moved repo to new place, that I wrote above https://github.com/OpenLinkSoftware/OSDS_extension

**Comment by ernstki** [comment]
@smalinin, OK, so basically to do header inspection then. That makes sense, thanks. `webRequestBlocking` is a bit of a misnomer in that case, but naming things _is_ hard.

> we moved repo to new place, that I wrote above https://github.com/OpenLinkSoftware/OSDS_extension

GitHub support should be able to migrate all the projects for you to the new org, right, if there are too many to do manually? Having two orgs is kind of confusing, especially when the Firefox extension points at the wrong one.

**Comment by smalinin** [comment]
The outdated info on https://osds.openlinksw.com/ will be fixed, I have wrote messages about this issue.

**Comment by smalinin** [comment]
`webRequestBlocking` isn't used in latest version(v: 3.4.8) of OSDS Firefox extension that is in Firefox Addons catalog already
https://addons.mozilla.org/ru/firefox/addon/openlink-structured-data-sniff

**Comment by ernstki** [comment]
> `webRequestBlocking` isn't used in latest version(v: 3.4.8) of OSDS Firefox extension that is in Firefox Addons catalog already https://addons.mozilla.org/ru/firefox/addon/openlink-structured-data-sniff

OK, thanks for pointing me in the right direction. Have a good week!
