### ISSUE TITLE
v2.13.9 FF version not working , link to v2.14 broken

### ISSUE THREAD

**Issue by 1u0n** [openlink/structured-data-sniffer#8]
(I'm on Firefox 51.0.1 on Windows 8)

the official firefox addon [release](https://addons.mozilla.org/firefox/addon/openlink-structured-data-sniff) installs but doesn't respond at all. The icon button doesn't perform any action, doesn't even behave like a button on hover. Only thing I see on browser console is

` onMsg=TypeError: request is null `

Debugging the JS I could only find this line in panel.js

 ` Browser.api.runtime.onMessage.addListener(function(request, sender, sendResponse) ` 

request parameter is null, hence it throws exception in its first line.

On other hand, the [link](https://github.com/openlink/structured-data-sniffer/releases/download/v2.14/OSDS_FF.zip) to the last version of FF extension on github doesn't work.

**Comment by duncanh** [comment]
Hmm I have the exact same problem - FF and plugin versions are the same, but on OS X 10.9.5 instead of Windows. It does work for me on Chrome 56.0 though, so will switch to that until there's a better option. Great tool though!

**Comment by smalinin** [comment]
The fixed FF version is 2.14.5 . It is ready and waiting the approve from Mozilla for Addon's store.

**Comment by 1u0n** [comment]
fixed for me!
